### ISSUE TITLE
Not able to use ssl_certkey on a vserver with service type SSL_TCP

### ISSUE THREAD

**Issue by miguelcastilho** [citrix/citrix-adc-ansible-modules#167] opened 2021-01-11 17:03 UTC
I'm using `citrix_adc_lb_vserver` to create a vserver with service type SSL_TCP. Documentation says `This option is only applicable only when servicetype is SSL.` and I get the same error when executing it.

On the GUI it is possible to bind a SSL certificate to a vserver with service type SSL_TCP.

Is there reason why I can't use the parameter `ssl_certkey` to bind a SSL certificate?

**Comment by vadharm** [comment] 2021-01-15 11:22
Needs triage.

**Comment by vadharm** [comment] 2021-01-15 11:27
@giorgos-nikolopoulos  - Can you triage and comment on this .

**Comment by giorgos-nikolopoulos** [comment] 2021-01-19 13:46
@miguelcastilho 
Is this issue happening only for ns-server-certificate  or for other certs also ?

**Comment by giorgos-nikolopoulos** [comment] 2021-01-19 13:46
@miguelcastilho 
Is this issue happening only for ns-server-certificate  or for other certs also ?

**Comment by miguelcastilho** [comment] 2021-01-19 15:29
@giorgos-nikolopoulos the issue is happening to uploaded certificates. I haven't tried using the ns-server-certificate.

**Comment by giorgos-nikolopoulos** [comment] 2021-03-04 09:10
I cannot reproduce the error.

The configuration below works as expected for me

```
resource "citrixadc_lbvserver" "tf_lbvserver" {
  ipv46       = "10.10.10.33"
  name        = "tf_lbvserver"
  port        = 80
  servicetype = "SSL_TCP"
  sslcertkey = "certificate_2"
}
```
In general if something works on nscli or GUI it will work with the provider.
All frontends use the same configuration engine.

I will close this since I cannot reproduce the error.

**Closed by giorgos-nikolopoulos** 2021-03-04 09:10 UTC
Labels: Triage
